name: Update Sözcü TV m3u link

on:
  schedule:
    - cron: '0 6 * * *'  
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Write cookies.txt
        run: echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Run update script
        run: python sozcu_yt.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add main.m3u
          git diff --cached --quiet || git commit -m "Sözcü TV M3U Güncellendi."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
